export const USERS_LOAD = "USERS_LOAD";

export const USER_DELETE = "USER_DELETE";
export const USERS_CONNECTION_LOAD = "USERS_CONNECTION_LOAD";
export const USER_CONNECTION_ADD = "USER_CONNECTION_ADD";
export const USER_CONNECTION_DELETE = "USER_CONNECTION_DELETE";

export const REQUESTS_CLEAR = "REQUEST_CLEAR";
export const REQUEST_BEGIN = "REQUEST_BEGIN";
export const REQUEST_RESPONSE = "REQUEST_RESPONSE";

export const ASSETS_PREVIEW_LOAD = "ASSETS_PREVIEW_LOAD";
export const ASSETS_HISTORY_LOAD = "ASSETS_HISTORY_LOAD";
export const ASSETS_LOAD = "ASSETS_LOAD";
export const ASSET_DISPLAY = "ASSET_DISPLAY";
export const ASSET_SENT = "ASSET_SENT";
export const ASSETS_CONNECTIONS_LOAD = "ASSETS_CONNECTIONS_LOAD";
export const ASSET_CONNECTION_ADD = "ASSET_CONNECTION_ADD";
export const ASSET_CONNECTION_DELETE = "ASSET_CONNECTION_DELETE";

export const SETTING_ASSETS_FILTER_DATE_FROM =
  "SETTING_ASSETS_FILTER_DATE_FROM";
export const SETTING_ASSETS_FILTER_DATE_TO = "SETTING_ASSETS_FILTER_DATE_TO";
export const SETTING_ASSETS_FILTER_USER = "SETTING_ASSETS_FILTER_USER";
export const SETTING_ASSETS_FILTER_GENERAL = "SETTING_ASSETS_FILTER_GENERAL";
export const SETTING_HISTORY_DAYS = "SETTING_HISTORY_DAYS";
